### ISSUE TITLE
Unhandled Exception for Missing Parameters

### ISSUE THREAD

**Issue by Digicrat** [krisdaniels/node-red-contrib#10]
If these is an error in the query generation specifying invalid parameters (due to a silly typo in my case), an uncaught exception brings down the entire node-red application instead of logging an error.  I'm guessing the contents of that function should be wrapped in a try{}...catch{} block, though I'm not certain what the correct error handling for Node-Red is in this case (I'm still new to node-red).

OTOH, node-red itself should likely also have an exception handler when it's calling into node modules, but one bug report a day is enough for me ;-)

15 Jul 13:03:38 - [red] Uncaught Exception:
15 Jul 13:03:38 - Error: Missing Parameters: device, nodeid, event
    at numericFromNamed (/home/david/.node-red/node_modules/node-postgres-named/main.js:20:11)
    at Client.patchedQuery [as query] (/home/david/.node-red/node_modules/node-postgres-named/main.js:62:25)
    at /home/david/.node-red/node_modules/node-red-contrib-postgres/postgres.js:127:18
    at BoundPool.<anonymous> (/home/david/.node-red/node_modules/pg-pool/index.js:137:9)
    at /home/david/.node-red/node_modules/generic-pool/lib/generic-pool.js:347:9
    at BoundPool.<anonymous> (/home/david/.node-red/node_modules/pg-pool/index.js:103:7)
    at Connection.<anonymous> (/home/david/.node-red/node_modules/pg/lib/client.js:158:7)
    at Object.onceWrapper (events.js:255:19)
    at Connection.emit (events.js:165:20)
    at Socket.<anonymous> (/home/david/.node-red/node_modules/pg/lib/connection.js:136:12)

**Comment by knolleary** [comment]
@Digicrat just fyi, Node-RED *does* have a global handler for uncaught exceptions - which is how we've been able to cleanly shutdown in this scenario. We do not swallow uncaught exceptions and keep running as we have no idea what state the system is in. The safest thing to do is trigger a restart of the runtime.

But ultimately, nodes need to handle their errors!
